// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebNet23Online.Data;

#nullable disable

namespace WebNet23Online.Data.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20260808092802_renameUserEntityFieldPasswordHash")]
    partial class renameUserEntityFieldPasswordHash
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FoodItemDataOrderData", b =>
                {
                    b.Property<int>("FoodItemsId")
                        .HasColumnType("int");

                    b.Property<int>("OrdersId")
                        .HasColumnType("int");

                    b.HasKey("FoodItemsId", "OrdersId");

                    b.HasIndex("OrdersId");

                    b.ToTable("FoodItemDataOrderData");
                });

            modelBuilder.Entity("UserDataUserData", b =>
                {
                    b.Property<int>("MyFriendsId")
                        .HasColumnType("int");

                    b.Property<int>("WhoIsMyFriendsId")
                        .HasColumnType("int");

                    b.HasKey("MyFriendsId", "WhoIsMyFriendsId");

                    b.HasIndex("WhoIsMyFriendsId");

                    b.ToTable("UserDataUserData");
                });

            modelBuilder.Entity("WebNet23Online.Data.DataModels.FoodItemIngredientData", b =>
                {
                    b.Property<int>("FoodItemDataId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientDataId")
                        .HasColumnType("int");

                    b.Property<decimal>("QuantityOfIngredients")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(10m);

                    b.HasKey("FoodItemDataId", "IngredientDataId");

                    b.HasIndex("IngredientDataId");

                    b.ToTable("FoodItemIngredientDatas", (string)null);
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("ImgURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MenuDataId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.HasIndex("MenuDataId");

                    b.ToTable("FoodItems");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CreatorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorId");

                    b.ToTable("Menus");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.NotificationData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TimeToPublish")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.OrderData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Language")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobilephone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<int?>("UserProfileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique()
                        .HasFilter("[UserProfileId] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FavBook")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PetName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfileData");
                });

            modelBuilder.Entity("FoodItemDataOrderData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.FoodItemData", null)
                        .WithMany()
                        .HasForeignKey("FoodItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.OrderData", null)
                        .WithMany()
                        .HasForeignKey("OrdersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserDataUserData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", null)
                        .WithMany()
                        .HasForeignKey("MyFriendsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.UserData", null)
                        .WithMany()
                        .HasForeignKey("WhoIsMyFriendsId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebNet23Online.Data.DataModels.FoodItemIngredientData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.FoodItemData", "FoodItemData")
                        .WithMany("FoodItemIngredientDatas")
                        .HasForeignKey("FoodItemDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebNet23Online.Data.Models.IngredientData", "IngredientData")
                        .WithMany("FoodItemIngredientDatas")
                        .HasForeignKey("IngredientDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItemData");

                    b.Navigation("IngredientData");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedFoodItems")
                        .HasForeignKey("CreatorId");

                    b.HasOne("WebNet23Online.Data.Models.MenuData", "MenuData")
                        .WithMany("FoodItems")
                        .HasForeignKey("MenuDataId");

                    b.Navigation("Creator");

                    b.Navigation("MenuData");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedIngredients")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Creator")
                        .WithMany("CreatedMenus")
                        .HasForeignKey("CreatorId");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.NotificationData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "Author")
                        .WithMany("Notifications")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.OrderData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserData", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.HasOne("WebNet23Online.Data.Models.UserProfileData", "UserProfile")
                        .WithOne("User")
                        .HasForeignKey("WebNet23Online.Data.Models.UserData", "UserProfileId");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.FoodItemData", b =>
                {
                    b.Navigation("FoodItemIngredientDatas");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.IngredientData", b =>
                {
                    b.Navigation("FoodItemIngredientDatas");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.MenuData", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserData", b =>
                {
                    b.Navigation("CreatedFoodItems");

                    b.Navigation("CreatedIngredients");

                    b.Navigation("CreatedMenus");

                    b.Navigation("Notifications");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("WebNet23Online.Data.Models.UserProfileData", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
