//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.HabitTracker {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HabitTracker {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HabitTracker() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.HabitTracker.HabitTracker", typeof(HabitTracker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string CreateHabit_btn_submit {
            get {
                return ResourceManager.GetString("CreateHabit-btn-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a habit.
        /// </summary>
        internal static string CreateHabit_card_title {
            get {
                return ResourceManager.GetString("CreateHabit-card-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal — days per month.
        /// </summary>
        internal static string CreateHabit_label_goal {
            get {
                return ResourceManager.GetString("CreateHabit-label-goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string CreateHabit_label_title {
            get {
                return ResourceManager.GetString("CreateHabit-label-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 31.
        /// </summary>
        internal static string CreateHabit_placeholder_goal {
            get {
                return ResourceManager.GetString("CreateHabit-placeholder-goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e.g. Yoga 15min.
        /// </summary>
        internal static string CreateHabit_placeholder_title {
            get {
                return ResourceManager.GetString("CreateHabit-placeholder-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add habit.
        /// </summary>
        internal static string CreateHabit_title {
            get {
                return ResourceManager.GetString("CreateHabit-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DeleteHabit_btn_submit {
            get {
                return ResourceManager.GetString("DeleteHabit-btn-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a habit.
        /// </summary>
        internal static string DeleteHabit_label_select {
            get {
                return ResourceManager.GetString("DeleteHabit-label-select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — select —.
        /// </summary>
        internal static string DeleteHabit_select_default {
            get {
                return ResourceManager.GetString("DeleteHabit-select-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete habit.
        /// </summary>
        internal static string DeleteHabit_title {
            get {
                return ResourceManager.GetString("DeleteHabit-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Diary_btn_cancel {
            get {
                return ResourceManager.GetString("Diary-btn-cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Diary_btn_save {
            get {
                return ResourceManager.GetString("Diary-btn-save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write something....
        /// </summary>
        internal static string Diary_placeholder {
            get {
                return ResourceManager.GetString("Diary-placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on a day to add an entry.
        /// </summary>
        internal static string Diary_subtitle {
            get {
                return ResourceManager.GetString("Diary-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diary.
        /// </summary>
        internal static string Diary_title {
            get {
                return ResourceManager.GetString("Diary-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string EditHabit_btn_submit {
            get {
                return ResourceManager.GetString("EditHabit-btn-submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goal — days per month.
        /// </summary>
        internal static string EditHabit_label_goal {
            get {
                return ResourceManager.GetString("EditHabit-label-goal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose a habit.
        /// </summary>
        internal static string EditHabit_label_select {
            get {
                return ResourceManager.GetString("EditHabit-label-select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string EditHabit_label_title {
            get {
                return ResourceManager.GetString("EditHabit-label-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to — select —.
        /// </summary>
        internal static string EditHabit_select_default {
            get {
                return ResourceManager.GetString("EditHabit-select-default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit habit.
        /// </summary>
        internal static string EditHabit_title {
            get {
                return ResourceManager.GetString("EditHabit-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fri.
        /// </summary>
        internal static string HabitTracker_day_fri {
            get {
                return ResourceManager.GetString("HabitTracker-day-fri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mon.
        /// </summary>
        internal static string HabitTracker_day_mon {
            get {
                return ResourceManager.GetString("HabitTracker-day-mon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sat.
        /// </summary>
        internal static string HabitTracker_day_sat {
            get {
                return ResourceManager.GetString("HabitTracker-day-sat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sun.
        /// </summary>
        internal static string HabitTracker_day_sun {
            get {
                return ResourceManager.GetString("HabitTracker-day-sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thu.
        /// </summary>
        internal static string HabitTracker_day_thu {
            get {
                return ResourceManager.GetString("HabitTracker-day-thu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tue.
        /// </summary>
        internal static string HabitTracker_day_tue {
            get {
                return ResourceManager.GetString("HabitTracker-day-tue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wed.
        /// </summary>
        internal static string HabitTracker_day_wed {
            get {
                return ResourceManager.GetString("HabitTracker-day-wed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today - .
        /// </summary>
        internal static string HabitTracker_tracker_date {
            get {
                return ResourceManager.GetString("HabitTracker-tracker-date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Task Tracker.
        /// </summary>
        internal static string HabitTracker_tracker_title {
            get {
                return ResourceManager.GetString("HabitTracker-tracker-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start tracking.
        /// </summary>
        internal static string Index_btn_primary {
            get {
                return ResourceManager.GetString("Index-btn-primary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore features.
        /// </summary>
        internal static string Index_btn_secondary {
            get {
                return ResourceManager.GetString("Index-btn-secondary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open my tracker →.
        /// </summary>
        internal static string Index_cta_btn {
            get {
                return ResourceManager.GetString("Index-cta-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join thousands of girls who are already building wonderful habits.
        /// </summary>
        internal static string Index_cta_subtitle {
            get {
                return ResourceManager.GetString("Index-cta-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start changing your life?.
        /// </summary>
        internal static string Index_cta_title {
            get {
                return ResourceManager.GetString("Index-cta-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A handy weekly table with colored dots. One click — and the habit is marked..
        /// </summary>
        internal static string Index_feature1_desc {
            get {
                return ResourceManager.GetString("Index-feature1-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Tracker.
        /// </summary>
        internal static string Index_feature1_title {
            get {
                return ResourceManager.GetString("Index-feature1-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress bars and exact completion percentage for the current month..
        /// </summary>
        internal static string Index_feature2_desc {
            get {
                return ResourceManager.GetString("Index-feature2-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Statistics.
        /// </summary>
        internal static string Index_feature2_title {
            get {
                return ResourceManager.GetString("Index-feature2-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful calendar. Click on any day and leave notes about your day..
        /// </summary>
        internal static string Index_feature3_desc {
            get {
                return ResourceManager.GetString("Index-feature3-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit Diary.
        /// </summary>
        internal static string Index_feature3_title {
            get {
                return ResourceManager.GetString("Index-feature3-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new habits, set a goal (days per month) and easily edit them..
        /// </summary>
        internal static string Index_feature4_desc {
            get {
                return ResourceManager.GetString("Index-feature4-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create &amp; Edit.
        /// </summary>
        internal static string Index_feature4_title {
            get {
                return ResourceManager.GetString("Index-feature4-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If a habit is no longer relevant — delete it in two clicks..
        /// </summary>
        internal static string Index_feature5_desc {
            get {
                return ResourceManager.GetString("Index-feature5-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Habits.
        /// </summary>
        internal static string Index_feature5_title {
            get {
                return ResourceManager.GetString("Index-feature5-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soft pink tones, smooth animations and attention to every detail..
        /// </summary>
        internal static string Index_feature6_desc {
            get {
                return ResourceManager.GetString("Index-feature6-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gentle Design.
        /// </summary>
        internal static string Index_feature6_title {
            get {
                return ResourceManager.GetString("Index-feature6-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everything you need to build lasting habits.
        /// </summary>
        internal static string Index_features_subtitle {
            get {
                return ResourceManager.GetString("Index-features-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit Tracker Features.
        /// </summary>
        internal static string Index_features_title {
            get {
                return ResourceManager.GetString("Index-features-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A beautiful and simple habit tracker created with love for aesthetics and discipline.
        /// </summary>
        internal static string Index_hero_subtitle {
            get {
                return ResourceManager.GetString("Index-hero-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habits that stay.
        /// </summary>
        internal static string Index_hero_title {
            get {
                return ResourceManager.GetString("Index-hero-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How does it work?.
        /// </summary>
        internal static string Index_how_title {
            get {
                return ResourceManager.GetString("Index-how-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Come up with a name and specify how many days a month you want to follow it..
        /// </summary>
        internal static string Index_step1_desc {
            get {
                return ResourceManager.GetString("Index-step1-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a habit.
        /// </summary>
        internal static string Index_step1_title {
            get {
                return ResourceManager.GetString("Index-step1-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the colored dots in the weekly tracker..
        /// </summary>
        internal static string Index_step2_desc {
            get {
                return ResourceManager.GetString("Index-step2-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track daily.
        /// </summary>
        internal static string Index_step2_title {
            get {
                return ResourceManager.GetString("Index-step2-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your statistics and keep a diary of moods and thoughts..
        /// </summary>
        internal static string Index_step3_desc {
            get {
                return ResourceManager.GetString("Index-step3-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monitor progress.
        /// </summary>
        internal static string Index_step3_title {
            get {
                return ResourceManager.GetString("Index-step3-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create →.
        /// </summary>
        internal static string Settings_add_btn {
            get {
                return ResourceManager.GetString("Settings-add-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new habit and set a monthly goal.
        /// </summary>
        internal static string Settings_add_desc {
            get {
                return ResourceManager.GetString("Settings-add-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Settings_add_label {
            get {
                return ResourceManager.GetString("Settings-add-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete →.
        /// </summary>
        internal static string Settings_del_btn {
            get {
                return ResourceManager.GetString("Settings-del-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove a habit you no longer track.
        /// </summary>
        internal static string Settings_del_desc {
            get {
                return ResourceManager.GetString("Settings-del-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Settings_del_label {
            get {
                return ResourceManager.GetString("Settings-del-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit →.
        /// </summary>
        internal static string Settings_edit_btn {
            get {
                return ResourceManager.GetString("Settings-edit-btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the name or goal of an existing habit.
        /// </summary>
        internal static string Settings_edit_desc {
            get {
                return ResourceManager.GetString("Settings-edit-desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Settings_edit_label {
            get {
                return ResourceManager.GetString("Settings-edit-label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage your habits.
        /// </summary>
        internal static string Settings_subtitle {
            get {
                return ResourceManager.GetString("Settings-subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Habit Settings.
        /// </summary>
        internal static string Settings_title {
            get {
                return ResourceManager.GetString("Settings-title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Statistics.
        /// </summary>
        internal static string Statistics_title {
            get {
                return ResourceManager.GetString("Statistics-title", resourceCulture);
            }
        }
    }
}
