//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations.HabitTracker {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HabitTracker {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HabitTracker() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.HabitTracker.HabitTracker", typeof(HabitTracker).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        // ── CreateHabit ──────────────────────────────────────────────────────────

        internal static string CreateHabit_btn_submit {
            get { return ResourceManager.GetString("CreateHabit-btn-submit", resourceCulture); }
        }

        internal static string CreateHabit_card_title {
            get { return ResourceManager.GetString("CreateHabit-card-title", resourceCulture); }
        }

        internal static string CreateHabit_label_goal {
            get { return ResourceManager.GetString("CreateHabit-label-goal", resourceCulture); }
        }

        internal static string CreateHabit_label_title {
            get { return ResourceManager.GetString("CreateHabit-label-title", resourceCulture); }
        }

        internal static string CreateHabit_placeholder_goal {
            get { return ResourceManager.GetString("CreateHabit-placeholder-goal", resourceCulture); }
        }

        internal static string CreateHabit_placeholder_title {
            get { return ResourceManager.GetString("CreateHabit-placeholder-title", resourceCulture); }
        }

        internal static string CreateHabit_title {
            get { return ResourceManager.GetString("CreateHabit-title", resourceCulture); }
        }

        // ── DeleteHabit ──────────────────────────────────────────────────────────

        internal static string DeleteHabit_btn_submit {
            get { return ResourceManager.GetString("DeleteHabit-btn-submit", resourceCulture); }
        }

        internal static string DeleteHabit_label_select {
            get { return ResourceManager.GetString("DeleteHabit-label-select", resourceCulture); }
        }

        internal static string DeleteHabit_select_default {
            get { return ResourceManager.GetString("DeleteHabit-select-default", resourceCulture); }
        }

        internal static string DeleteHabit_title {
            get { return ResourceManager.GetString("DeleteHabit-title", resourceCulture); }
        }

        // ── Diary ────────────────────────────────────────────────────────────────

        internal static string Diary_btn_cancel {
            get { return ResourceManager.GetString("Diary-btn-cancel", resourceCulture); }
        }

        internal static string Diary_btn_save {
            get { return ResourceManager.GetString("Diary-btn-save", resourceCulture); }
        }

        internal static string Diary_placeholder {
            get { return ResourceManager.GetString("Diary-placeholder", resourceCulture); }
        }

        internal static string Diary_subtitle {
            get { return ResourceManager.GetString("Diary-subtitle", resourceCulture); }
        }

        internal static string Diary_title {
            get { return ResourceManager.GetString("Diary-title", resourceCulture); }
        }

        // ── EditHabit ────────────────────────────────────────────────────────────

        internal static string EditHabit_btn_submit {
            get { return ResourceManager.GetString("EditHabit-btn-submit", resourceCulture); }
        }

        internal static string EditHabit_label_goal {
            get { return ResourceManager.GetString("EditHabit-label-goal", resourceCulture); }
        }

        internal static string EditHabit_label_select {
            get { return ResourceManager.GetString("EditHabit-label-select", resourceCulture); }
        }

        internal static string EditHabit_label_title {
            get { return ResourceManager.GetString("EditHabit-label-title", resourceCulture); }
        }

        internal static string EditHabit_select_default {
            get { return ResourceManager.GetString("EditHabit-select-default", resourceCulture); }
        }

        internal static string EditHabit_title {
            get { return ResourceManager.GetString("EditHabit-title", resourceCulture); }
        }

        // ── HabitTracker (main view) ──────────────────────────────────────────────

        internal static string HabitTracker_day_fri {
            get { return ResourceManager.GetString("HabitTracker-day-fri", resourceCulture); }
        }

        internal static string HabitTracker_day_mon {
            get { return ResourceManager.GetString("HabitTracker-day-mon", resourceCulture); }
        }

        internal static string HabitTracker_day_sat {
            get { return ResourceManager.GetString("HabitTracker-day-sat", resourceCulture); }
        }

        internal static string HabitTracker_day_sun {
            get { return ResourceManager.GetString("HabitTracker-day-sun", resourceCulture); }
        }

        internal static string HabitTracker_day_thu {
            get { return ResourceManager.GetString("HabitTracker-day-thu", resourceCulture); }
        }

        internal static string HabitTracker_day_tue {
            get { return ResourceManager.GetString("HabitTracker-day-tue", resourceCulture); }
        }

        internal static string HabitTracker_day_wed {
            get { return ResourceManager.GetString("HabitTracker-day-wed", resourceCulture); }
        }

        internal static string HabitTracker_tracker_date {
            get { return ResourceManager.GetString("HabitTracker-tracker-date", resourceCulture); }
        }

        internal static string HabitTracker_tracker_title {
            get { return ResourceManager.GetString("HabitTracker-tracker-title", resourceCulture); }
        }

        // ── Index ────────────────────────────────────────────────────────────────

        internal static string Index_btn_primary {
            get { return ResourceManager.GetString("Index-btn-primary", resourceCulture); }
        }

        internal static string Index_btn_secondary {
            get { return ResourceManager.GetString("Index-btn-secondary", resourceCulture); }
        }

        internal static string Index_cta_btn {
            get { return ResourceManager.GetString("Index-cta-btn", resourceCulture); }
        }

        internal static string Index_cta_subtitle {
            get { return ResourceManager.GetString("Index-cta-subtitle", resourceCulture); }
        }

        internal static string Index_cta_title {
            get { return ResourceManager.GetString("Index-cta-title", resourceCulture); }
        }

        internal static string Index_feature1_desc {
            get { return ResourceManager.GetString("Index-feature1-desc", resourceCulture); }
        }

        internal static string Index_feature1_title {
            get { return ResourceManager.GetString("Index-feature1-title", resourceCulture); }
        }

        internal static string Index_feature2_desc {
            get { return ResourceManager.GetString("Index-feature2-desc", resourceCulture); }
        }

        internal static string Index_feature2_title {
            get { return ResourceManager.GetString("Index-feature2-title", resourceCulture); }
        }

        internal static string Index_feature3_desc {
            get { return ResourceManager.GetString("Index-feature3-desc", resourceCulture); }
        }

        internal static string Index_feature3_title {
            get { return ResourceManager.GetString("Index-feature3-title", resourceCulture); }
        }

        internal static string Index_feature4_desc {
            get { return ResourceManager.GetString("Index-feature4-desc", resourceCulture); }
        }

        internal static string Index_feature4_title {
            get { return ResourceManager.GetString("Index-feature4-title", resourceCulture); }
        }

        internal static string Index_feature5_desc {
            get { return ResourceManager.GetString("Index-feature5-desc", resourceCulture); }
        }

        internal static string Index_feature5_title {
            get { return ResourceManager.GetString("Index-feature5-title", resourceCulture); }
        }

        internal static string Index_feature6_desc {
            get { return ResourceManager.GetString("Index-feature6-desc", resourceCulture); }
        }

        internal static string Index_feature6_title {
            get { return ResourceManager.GetString("Index-feature6-title", resourceCulture); }
        }

        internal static string Index_features_subtitle {
            get { return ResourceManager.GetString("Index-features-subtitle", resourceCulture); }
        }

        internal static string Index_features_title {
            get { return ResourceManager.GetString("Index-features-title", resourceCulture); }
        }

        internal static string Index_hero_subtitle {
            get { return ResourceManager.GetString("Index-hero-subtitle", resourceCulture); }
        }

        internal static string Index_hero_title {
            get { return ResourceManager.GetString("Index-hero-title", resourceCulture); }
        }

        internal static string Index_how_title {
            get { return ResourceManager.GetString("Index-how-title", resourceCulture); }
        }

        internal static string Index_step1_desc {
            get { return ResourceManager.GetString("Index-step1-desc", resourceCulture); }
        }

        internal static string Index_step1_title {
            get { return ResourceManager.GetString("Index-step1-title", resourceCulture); }
        }

        internal static string Index_step2_desc {
            get { return ResourceManager.GetString("Index-step2-desc", resourceCulture); }
        }

        internal static string Index_step2_title {
            get { return ResourceManager.GetString("Index-step2-title", resourceCulture); }
        }

        internal static string Index_step3_desc {
            get { return ResourceManager.GetString("Index-step3-desc", resourceCulture); }
        }

        internal static string Index_step3_title {
            get { return ResourceManager.GetString("Index-step3-title", resourceCulture); }
        }

        // ── Settings ─────────────────────────────────────────────────────────────

        internal static string Settings_add_btn {
            get { return ResourceManager.GetString("Settings-add-btn", resourceCulture); }
        }

        internal static string Settings_add_desc {
            get { return ResourceManager.GetString("Settings-add-desc", resourceCulture); }
        }

        internal static string Settings_add_label {
            get { return ResourceManager.GetString("Settings-add-label", resourceCulture); }
        }

        internal static string Settings_del_btn {
            get { return ResourceManager.GetString("Settings-del-btn", resourceCulture); }
        }

        internal static string Settings_del_desc {
            get { return ResourceManager.GetString("Settings-del-desc", resourceCulture); }
        }

        internal static string Settings_del_label {
            get { return ResourceManager.GetString("Settings-del-label", resourceCulture); }
        }

        internal static string Settings_edit_btn {
            get { return ResourceManager.GetString("Settings-edit-btn", resourceCulture); }
        }

        internal static string Settings_edit_desc {
            get { return ResourceManager.GetString("Settings-edit-desc", resourceCulture); }
        }

        internal static string Settings_edit_label {
            get { return ResourceManager.GetString("Settings-edit-label", resourceCulture); }
        }

        internal static string Settings_subtitle {
            get { return ResourceManager.GetString("Settings-subtitle", resourceCulture); }
        }

        internal static string Settings_title {
            get { return ResourceManager.GetString("Settings-title", resourceCulture); }
        }

        // ── Statistics ───────────────────────────────────────────────────────────

        internal static string Statistics_title {
            get { return ResourceManager.GetString("Statistics-title", resourceCulture); }
        }
    }
}
