//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JapaneseDomesticMarket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JapaneseDomesticMarket() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.JapaneseDomesticMarket", typeof(JapaneseDomesticMarket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string _JournalPartial_Button_Send {
            get {
                return ResourceManager.GetString("_JournalPartial_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in to leave a comment.
        /// </summary>
        public static string _JournalPartial_Login {
            get {
                return ResourceManager.GetString("_JournalPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More details.
        /// </summary>
        public static string Catalog_Button_More_Details {
            get {
                return ResourceManager.GetString("Catalog_Button_More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehical History.
        /// </summary>
        public static string Catalog_Statistics_VehicalHistory {
            get {
                return ResourceManager.GetString("Catalog_Statistics_VehicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach a photo.
        /// </summary>
        public static string CreateCars_Attach_Photo {
            get {
                return ResourceManager.GetString("CreateCars_Attach_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        public static string CreateCars_Brand {
            get {
                return ResourceManager.GetString("CreateCars_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach the vehicle inspection history.
        /// </summary>
        public static string CreateCars_Headers_Vehicle_Inspection_History {
            get {
                return ResourceManager.GetString("CreateCars_Headers_Vehicle_Inspection_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string CreateCars_Manufacturer {
            get {
                return ResourceManager.GetString("CreateCars_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string CreateCars_Model {
            get {
                return ResourceManager.GetString("CreateCars_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string CreateCars_Send_Button {
            get {
                return ResourceManager.GetString("CreateCars_Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to April 19, 2026.
        /// </summary>
        public static string Journal_Date_19_April {
            get {
                return ResourceManager.GetString("Journal_Date_19_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to August 30, 2025.
        /// </summary>
        public static string Journal_Date_30_August {
            get {
                return ResourceManager.GetString("Journal_Date_30_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s get acquainted!.
        /// </summary>
        public static string Journal_Header {
            get {
                return ResourceManager.GetString("Journal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hundreds of participants and guests gathered on the grounds of Lida Castle to enjoy the festive atmosphere, see unique cars, and share experiences..
        /// </summary>
        public static string Journal_Text_Lida_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Lida_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It was noisy! It was smoky! It was awesome! I declare the drift season officially open! I don&apos;t know how many sets of tires the guys had to change during all the runs,.
        /// </summary>
        public static string Journal_Text_Raubichi_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but the fact is that tires and wheels flew off today! Bumpers and hoods flew off... Some pilots got too close to the walls and concrete blocks..
        /// </summary>
        public static string Journal_Text_Raubichi_2 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos can&apos;t capture the full furor; one can only try. So, I&apos;m sharing my favorite photos..
        /// </summary>
        public static string Journal_Text_Raubichi_3 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once upon a time, when I took a test, I could recognize more than 180 car logos..
        /// </summary>
        public static string Journal_Text_Test_Models {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.S. This is a skill that has never been useful in life..
        /// </summary>
        public static string Journal_Text_Test_Models_h2 {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cars Picnic in Lida.
        /// </summary>
        public static string Journal_Title_Header_2 {
            get {
                return ResourceManager.GetString("Journal_Title_Header_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening of the 2026 drift season, Raubichi.
        /// </summary>
        public static string Journal_Title_Header_Raubichi {
            get {
                return ResourceManager.GetString("Journal_Title_Header_Raubichi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The motivation for creating this online portal was my love for JDM culture and the atmosphere that reigns at car gatherings..
        /// </summary>
        public static string Journal_Welcome_Line {
            get {
                return ResourceManager.GetString("Journal_Welcome_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertisements.
        /// </summary>
        public static string Layout_Advertisements {
            get {
                return ResourceManager.GetString("Layout_Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal.
        /// </summary>
        public static string Layout_Journal {
            get {
                return ResourceManager.GetString("Layout_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell car.
        /// </summary>
        public static string Layout_Sell_Car {
            get {
                return ResourceManager.GetString("Layout_Sell_Car", resourceCulture);
            }
        }
    }
}
