//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class JapaneseDomesticMarket {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal JapaneseDomesticMarket() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.JapaneseDomesticMarket", typeof(JapaneseDomesticMarket).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string _JournalPartial_Button_Send {
            get {
                return ResourceManager.GetString("_JournalPartial_Button_Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Log in to leave a comment.
        /// </summary>
        public static string _JournalPartial_Login {
            get {
                return ResourceManager.GetString("_JournalPartial_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Interested in the ad? Call the number.
        /// </summary>
        public static string Button_Call_The_Number {
            get {
                return ResourceManager.GetString("Button_Call_The_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The seller did not provide a phone number..
        /// </summary>
        public static string Button_Call_The_Number_NoPhone {
            get {
                return ResourceManager.GetString("Button_Call_The_Number_NoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        public static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add merch.
        /// </summary>
        public static string Catalog_button_add_merch {
            get {
                return ResourceManager.GetString("Catalog_button_add_merch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на More details.
        /// </summary>
        public static string Catalog_Button_More_Details {
            get {
                return ResourceManager.GetString("Catalog_Button_More_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product catalog.
        /// </summary>
        public static string Catalog_header_catalog_product {
            get {
                return ResourceManager.GetString("Catalog_header_catalog_product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vehical History.
        /// </summary>
        public static string Catalog_Statistics_VehicalHistory {
            get {
                return ResourceManager.GetString("Catalog_Statistics_VehicalHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach a photo.
        /// </summary>
        public static string CreateCars_Attach_Photo {
            get {
                return ResourceManager.GetString("CreateCars_Attach_Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Brand.
        /// </summary>
        public static string CreateCars_Brand {
            get {
                return ResourceManager.GetString("CreateCars_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attach the vehicle inspection history.
        /// </summary>
        public static string CreateCars_Headers_Vehicle_Inspection_History {
            get {
                return ResourceManager.GetString("CreateCars_Headers_Vehicle_Inspection_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter brand.
        /// </summary>
        public static string CreateCars_input_marka {
            get {
                return ResourceManager.GetString("CreateCars_input_marka", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter model.
        /// </summary>
        public static string CreateCars_input_model {
            get {
                return ResourceManager.GetString("CreateCars_input_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Enter price.
        /// </summary>
        public static string CreateCars_input_price {
            get {
                return ResourceManager.GetString("CreateCars_input_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manufacturer.
        /// </summary>
        public static string CreateCars_Manufacturer {
            get {
                return ResourceManager.GetString("CreateCars_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Model.
        /// </summary>
        public static string CreateCars_Model {
            get {
                return ResourceManager.GetString("CreateCars_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Send.
        /// </summary>
        public static string CreateCars_Send_Button {
            get {
                return ResourceManager.GetString("CreateCars_Send_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Price.
        /// </summary>
        public static string CteateCars_header_price {
            get {
                return ResourceManager.GetString("CteateCars_header_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete old post&apos;s.
        /// </summary>
        public static string Journal_button_delete_post {
            get {
                return ResourceManager.GetString("Journal_button_delete_post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на April 19, 2026.
        /// </summary>
        public static string Journal_Date_19_April {
            get {
                return ResourceManager.GetString("Journal_Date_19_April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на August 30, 2025.
        /// </summary>
        public static string Journal_Date_30_August {
            get {
                return ResourceManager.GetString("Journal_Date_30_August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Let&apos;s get acquainted!.
        /// </summary>
        public static string Journal_Header {
            get {
                return ResourceManager.GetString("Journal_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hundreds of participants and guests gathered on the grounds of Lida Castle to enjoy the festive atmosphere, see unique cars, and share experiences..
        /// </summary>
        public static string Journal_Text_Lida_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Lida_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на It was noisy! It was smoky! It was awesome! I declare the drift season officially open! I don&apos;t know how many sets of tires the guys had to change during all the runs,.
        /// </summary>
        public static string Journal_Text_Raubichi_1 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на but the fact is that tires and wheels flew off today! Bumpers and hoods flew off... Some pilots got too close to the walls and concrete blocks..
        /// </summary>
        public static string Journal_Text_Raubichi_2 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Photos can&apos;t capture the full furor; one can only try. So, I&apos;m sharing my favorite photos..
        /// </summary>
        public static string Journal_Text_Raubichi_3 {
            get {
                return ResourceManager.GetString("Journal_Text_Raubichi_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Once upon a time, when I took a test, I could recognize more than 180 car logos..
        /// </summary>
        public static string Journal_Text_Test_Models {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на P.S. This is a skill that has never been useful in life..
        /// </summary>
        public static string Journal_Text_Test_Models_h2 {
            get {
                return ResourceManager.GetString("Journal_Text_Test_Models_h2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cars Picnic in Lida.
        /// </summary>
        public static string Journal_Title_Header_2 {
            get {
                return ResourceManager.GetString("Journal_Title_Header_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Opening of the 2026 drift season, Raubichi.
        /// </summary>
        public static string Journal_Title_Header_Raubichi {
            get {
                return ResourceManager.GetString("Journal_Title_Header_Raubichi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The motivation for creating this online portal was my love for JDM culture and the atmosphere that reigns at car gatherings..
        /// </summary>
        public static string Journal_Welcome_Line {
            get {
                return ResourceManager.GetString("Journal_Welcome_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advertisements.
        /// </summary>
        public static string Layout_Advertisements {
            get {
                return ResourceManager.GetString("Layout_Advertisements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Journal.
        /// </summary>
        public static string Layout_Journal {
            get {
                return ResourceManager.GetString("Layout_Journal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sell car.
        /// </summary>
        public static string Layout_Sell_Car {
            get {
                return ResourceManager.GetString("Layout_Sell_Car", resourceCulture);
            }
        }
    }
}
