//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LittleLemon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LittleLemon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.LittleLemon", typeof(LittleLemon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Layout_About {
            get {
                return ResourceManager.GetString("Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Layout_Contact {
            get {
                return ResourceManager.GetString("Layout_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Layout_Home {
            get {
                return ResourceManager.GetString("Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Layout_Login {
            get {
                return ResourceManager.GetString("Layout_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Layout_Logout {
            get {
                return ResourceManager.GetString("Layout_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Layout_Menu {
            get {
                return ResourceManager.GetString("Layout_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Online.
        /// </summary>
        public static string Layout_OrderOnline {
            get {
                return ResourceManager.GetString("Layout_OrderOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Layout_Reservation {
            get {
                return ResourceManager.GetString("Layout_Reservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type your E-mail.
        /// </summary>
        public static string Layout_Subscribe_EmailPlaceholder {
            get {
                return ResourceManager.GetString("Layout_Subscribe_EmailPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe!.
        /// </summary>
        public static string Layout_Subscribe_Label {
            get {
                return ResourceManager.GetString("Layout_Subscribe_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to submit.
        /// </summary>
        public static string Layout_Subscribe_Submit {
            get {
                return ResourceManager.GetString("Layout_Subscribe_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Little Lemon restaurant.
        /// </summary>
        public static string Layout_Title {
            get {
                return ResourceManager.GetString("Layout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date:.
        /// </summary>
        public static string Reservation_ChooseDate {
            get {
                return ResourceManager.GetString("Reservation_ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Time:.
        /// </summary>
        public static string Reservation_ChooseTime {
            get {
                return ResourceManager.GetString("Reservation_ChooseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember, be nice!.
        /// </summary>
        public static string Reservation_CommentsPlaceholder {
            get {
                return ResourceManager.GetString("Reservation_CommentsPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You want to add anything else?.
        /// </summary>
        public static string Reservation_ExtraLabel {
            get {
                return ResourceManager.GetString("Reservation_ExtraLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest name:.
        /// </summary>
        public static string Reservation_GuestName {
            get {
                return ResourceManager.GetString("Reservation_GuestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Loving Place!.
        /// </summary>
        public static string Reservation_Header {
            get {
                return ResourceManager.GetString("Reservation_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indoor dining room.
        /// </summary>
        public static string Reservation_Indoor {
            get {
                return ResourceManager.GetString("Reservation_Indoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No preference.
        /// </summary>
        public static string Reservation_NoPreference {
            get {
                return ResourceManager.GetString("Reservation_NoPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Guests:.
        /// </summary>
        public static string Reservation_NumberOfGuests {
            get {
                return ResourceManager.GetString("Reservation_NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasion:.
        /// </summary>
        public static string Reservation_Occasion {
            get {
                return ResourceManager.GetString("Reservation_Occasion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniversary.
        /// </summary>
        public static string Reservation_Occasion_Anniversary {
            get {
                return ResourceManager.GetString("Reservation_Occasion_Anniversary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        public static string Reservation_Occasion_Birthday {
            get {
                return ResourceManager.GetString("Reservation_Occasion_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Reservation_Occasion_None {
            get {
                return ResourceManager.GetString("Reservation_Occasion_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Reservation_Occasion_Other {
            get {
                return ResourceManager.GetString("Reservation_Occasion_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        public static string Reservation_PageTitle {
            get {
                return ResourceManager.GetString("Reservation_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patio / outdoor.
        /// </summary>
        public static string Reservation_Patio {
            get {
                return ResourceManager.GetString("Reservation_Patio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seating preference:.
        /// </summary>
        public static string Reservation_SeatingPreference {
            get {
                return ResourceManager.GetString("Reservation_SeatingPreference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make your reservation.
        /// </summary>
        public static string Reservation_Submit {
            get {
                return ResourceManager.GetString("Reservation_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window table (if available).
        /// </summary>
        public static string Reservation_Window {
            get {
                return ResourceManager.GetString("Reservation_Window", resourceCulture);
            }
        }
    }
}
