//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SlayTheSpire2Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlayTheSpire2Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.SlayTheSpire2Index", typeof(SlayTheSpire2Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string Index_HeroName_Defect {
            get {
                return ResourceManager.GetString("Index_HeroName_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ironclad.
        /// </summary>
        public static string Index_HeroName_Ironclad {
            get {
                return ResourceManager.GetString("Index_HeroName_Ironclad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necrobinder.
        /// </summary>
        public static string Index_HeroName_Necrobinder {
            get {
                return ResourceManager.GetString("Index_HeroName_Necrobinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regent.
        /// </summary>
        public static string Index_HeroName_Regent {
            get {
                return ResourceManager.GetString("Index_HeroName_Regent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Silent.
        /// </summary>
        public static string Index_HeroName_Silent {
            get {
                return ResourceManager.GetString("Index_HeroName_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;For a thousand years the Spire has slumbered... Now it has opened again, hungrier and more dangerous than ever, devouring all who dare to climb.&quot;.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainPage.
        /// </summary>
        public static string Layout_MainPage {
            get {
                return ResourceManager.GetString("Layout_MainPage", resourceCulture);
            }
        }
    }
}
