//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNet23Online.Localizations {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SlayTheSpire2Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SlayTheSpire2Index() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebNet23Online.Localizations.SlayTheSpire2Index", typeof(SlayTheSpire2Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Defect.
        /// </summary>
        public static string Index_HeroName_Defect {
            get {
                return ResourceManager.GetString("Index_HeroName_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ironclad.
        /// </summary>
        public static string Index_HeroName_Ironclad {
            get {
                return ResourceManager.GetString("Index_HeroName_Ironclad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Necrobinder.
        /// </summary>
        public static string Index_HeroName_Necrobinder {
            get {
                return ResourceManager.GetString("Index_HeroName_Necrobinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regent.
        /// </summary>
        public static string Index_HeroName_Regent {
            get {
                return ResourceManager.GetString("Index_HeroName_Regent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Silent.
        /// </summary>
        public static string Index_HeroName_Silent {
            get {
                return ResourceManager.GetString("Index_HeroName_Silent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &quot;For a thousand years the Spire has slumbered... Now it has opened again, hungrier and more dangerous than ever, devouring all who dare to climb.&quot;.
        /// </summary>
        public static string Index_Title {
            get {
                return ResourceManager.GetString("Index_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MainPage.
        /// </summary>
        public static string Layout_MainPage {
            get {
                return ResourceManager.GetString("Layout_MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relics.
        /// </summary>
        public static string Layout_Relics {
            get {
                return ResourceManager.GetString("Layout_Relics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string Relics_CreateButton {
            get {
                return ResourceManager.GetString("Relics_CreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Relic.
        /// </summary>
        public static string Relics_CreateTitle {
            get {
                return ResourceManager.GetString("Relics_CreateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string Relics_NamePlaceholder {
            get {
                return ResourceManager.GetString("Relics_NamePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Relics.
        /// </summary>
        public static string Relics_PageTitle {
            get {
                return ResourceManager.GetString("Relics_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rarity.
        /// </summary>
        public static string Relics_RarityLabel {
            get {
                return ResourceManager.GetString("Relics_RarityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rarity.
        /// </summary>
        public static string Relics_RarityPlaceholder {
            get {
                return ResourceManager.GetString("Relics_RarityPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name, Rarity and image relic.
        /// </summary>
        public static string Relics_SectionIntro {
            get {
                return ResourceManager.GetString("Relics_SectionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на URL image.
        /// </summary>
        public static string Relics_UrlPlaceholder {
            get {
                return ResourceManager.GetString("Relics_UrlPlaceholder", resourceCulture);
            }
        }
    }
}
